version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './app:/var/www/html'
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - my_network

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    networks:
      - my_network

networks:
  my_network:
